
name: Test

on: [push]

jobs:
  test:
    runs-on: macos-12
    name: A job to run test in NetBSD
    env:
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v3
    - name: Test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v0
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          /usr/sbin/pkg_add curl

        run: |
          pwd
          ls -lah
          whoami
          env
