name: netbsd CI
'on': push
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: FreeBSD VM
        id: vm
        uses: vmactions/freebsd-vm@v0
        with:
          prepare: |
            pkg install -y curl
            pkg install -y sudo
            pkg install -y gcc
            pkg install -y rust
          run: |
            sudo pkg install llvm
            sudo pkg install llvm16
            llvm-config --version
            clang --version
            rustc --version
