name: netbsd CI
'on': push
jobs:
  build:
    runs-on: macos-12
    env:
        INPUT_RUST_VERSION: 1.72
    steps:  
      - name: Checkout code
        uses: actions/checkout@v3
      - name: FreeBSD VM
        id: vm
        uses: vmactions/freebsd-vm@v0
        with:
          envs: 'INPUT_RUST_VERSION'
          usesh: true
          run: |
            pkg search llvm
