name: Windows CI

on: [push, pull_request]

jobs:
  x86_64-windows-llvm:
    runs-on: windows-2022
    steps:
      - run: echo $(pwd)\llvm
      - run: mkdir test

      - run: echo ..\$(pwd)\llvm
        working-directory: ./test

      - run: |
          cd ..\$(pwd)\test
          cd
        working-directory: ./test
